# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'voice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvoice.proto\x12\x05voice\"2\n\rSpeechRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0bvoice_model\x18\x02 \x01(\t\"%\n\x0eSpeechResponse\x12\x13\n\x0b\x61udio_chunk\x18\x01 \x01(\x0c\x32O\n\x0cVoiceService\x12?\n\x0eGenerateSpeech\x12\x14.voice.SpeechRequest\x1a\x15.voice.SpeechResponse0\x01\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_SPEECHREQUEST']._serialized_start=22
  _globals['_SPEECHREQUEST']._serialized_end=72
  _globals['_SPEECHRESPONSE']._serialized_start=74
  _globals['_SPEECHRESPONSE']._serialized_end=111
  _globals['_VOICESERVICE']._serialized_start=113
  _globals['_VOICESERVICE']._serialized_end=192
# @@protoc_insertion_point(module_scope)
