# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvoice.proto\x12\x05voice\"\x1c\n\x0cSpeakRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"1\n\rSpeakResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2B\n\x0cVoiceService\x12\x32\n\x05Speak\x12\x13.voice.SpeakRequest\x1a\x14.voice.SpeakResponseB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_SPEAKREQUEST']._serialized_start=22
  _globals['_SPEAKREQUEST']._serialized_end=50
  _globals['_SPEAKRESPONSE']._serialized_start=52
  _globals['_SPEAKRESPONSE']._serialized_end=101
  _globals['_VOICESERVICE']._serialized_start=103
  _globals['_VOICESERVICE']._serialized_end=169
# @@protoc_insertion_point(module_scope)
