package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"strconv"

	pb "github.com/roopesharch/EchoSonic/gateway-go/proto"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

func main() {
	// Connect to the Python AI Engine (Internal Docker Communication)
	conn, err := grpc.Dial("127.0.0.1:50051", grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		log.Fatalf("Failed to connect to AI Engine: %v", err)
	}
	defer conn.Close()
	client := pb.NewVoiceServiceClient(conn)

	// Handle the /speak endpoint
	http.HandleFunc("/speak", func(w http.ResponseWriter, r *http.Request) {
		// --- CORS HEADERS ---
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type")

		if r.Method == "OPTIONS" {
			w.WriteHeader(http.StatusOK)
			return
		}

		// --- LOGIC ---
		r.ParseForm()
		speed, _ := strconv.ParseFloat(r.FormValue("speed"), 32)
		noise, _ := strconv.ParseFloat(r.FormValue("noise"), 32)

		_, err := client.Speak(context.Background(), &pb.SpeakRequest{
			Text:  r.FormValue("text"),
			Voice: r.FormValue("voice"),
			Speed: float32(speed),
			Noise: float32(noise),
		})

		if err != nil {
			log.Printf("AI Engine Error: %v", err)
			w.WriteHeader(http.StatusInternalServerError)
			return
		}

		w.WriteHeader(http.StatusOK)
		fmt.Fprint(w, "Success")
	})

	// Handle the /listen endpoint
	http.HandleFunc("/listen", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Content-Type", "audio/wav")
		w.Header().Set("Cache-Control", "no-cache, no-store, must-revalidate")

		// Look for the output file generated by Python
		http.ServeFile(w, r, "../engine-python/output.wav")
	})

	// Get port from environment (Render requirement)
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	fmt.Printf("🌐 EchoSonic Gateway Live on Port %s\n", port)
	log.Fatal(http.ListenAndServe(":"+port, nil))
}
