// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: voice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpeakRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Voice         string                 `protobuf:"bytes,2,opt,name=voice,proto3" json:"voice,omitempty"`
	Speed         float32                `protobuf:"fixed32,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Noise         float32                `protobuf:"fixed32,4,opt,name=noise,proto3" json:"noise,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeakRequest) Reset() {
	*x = SpeakRequest{}
	mi := &file_voice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeakRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeakRequest) ProtoMessage() {}

func (x *SpeakRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeakRequest.ProtoReflect.Descriptor instead.
func (*SpeakRequest) Descriptor() ([]byte, []int) {
	return file_voice_proto_rawDescGZIP(), []int{0}
}

func (x *SpeakRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SpeakRequest) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *SpeakRequest) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *SpeakRequest) GetNoise() float32 {
	if x != nil {
		return x.Noise
	}
	return 0
}

type SpeakResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeakResponse) Reset() {
	*x = SpeakResponse{}
	mi := &file_voice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeakResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeakResponse) ProtoMessage() {}

func (x *SpeakResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeakResponse.ProtoReflect.Descriptor instead.
func (*SpeakResponse) Descriptor() ([]byte, []int) {
	return file_voice_proto_rawDescGZIP(), []int{1}
}

func (x *SpeakResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SpeakResponse) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

var File_voice_proto protoreflect.FileDescriptor

const file_voice_proto_rawDesc = "" +
	"\n" +
	"\vvoice.proto\x12\x05voice\"d\n" +
	"\fSpeakRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05voice\x18\x02 \x01(\tR\x05voice\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x02R\x05speed\x12\x14\n" +
	"\x05noise\x18\x04 \x01(\x02R\x05noise\"H\n" +
	"\rSpeakResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x02 \x01(\fR\taudioData2B\n" +
	"\fVoiceService\x122\n" +
	"\x05Speak\x12\x13.voice.SpeakRequest\x1a\x14.voice.SpeakResponseB\tZ\a./protob\x06proto3"

var (
	file_voice_proto_rawDescOnce sync.Once
	file_voice_proto_rawDescData []byte
)

func file_voice_proto_rawDescGZIP() []byte {
	file_voice_proto_rawDescOnce.Do(func() {
		file_voice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voice_proto_rawDesc), len(file_voice_proto_rawDesc)))
	})
	return file_voice_proto_rawDescData
}

var file_voice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_voice_proto_goTypes = []any{
	(*SpeakRequest)(nil),  // 0: voice.SpeakRequest
	(*SpeakResponse)(nil), // 1: voice.SpeakResponse
}
var file_voice_proto_depIdxs = []int32{
	0, // 0: voice.VoiceService.Speak:input_type -> voice.SpeakRequest
	1, // 1: voice.VoiceService.Speak:output_type -> voice.SpeakResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_voice_proto_init() }
func file_voice_proto_init() {
	if File_voice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voice_proto_rawDesc), len(file_voice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voice_proto_goTypes,
		DependencyIndexes: file_voice_proto_depIdxs,
		MessageInfos:      file_voice_proto_msgTypes,
	}.Build()
	File_voice_proto = out.File
	file_voice_proto_goTypes = nil
	file_voice_proto_depIdxs = nil
}
